### ISSUE TITLE
Add Interactive String Calculator Kata

### ISSUE THREAD

**Issue by prometheas** [prometheas/OLD-generator-multistack-tdd-kata#4]
Add Osherove's ["Interactions" kata](http://osherove.com/tdd-kata-2).

**Comment by garora** [comment]
@prometheas - its already added in [TDD-Katas](https://github.com/garora/TDD-Katas]). @boogie666 has adapted the same repository tests and I was contributing there. It seems he is not active as, I am not seeing much pushes into his repository. So, whats your plan to make your repository uptodate with new tests (added in my repository). Do you like if I contributed in your repository?

**Comment by prometheas** [comment]
I'd actually already added this locally a few days ago (but forgot to push it)! This is resolved by 0d5729fd29451156a532d9ae753a4eadb37abe58.

Thank you for your kind offer, @garora :)
